apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcolor1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webcolor1
  template:
    metadata:
      labels:
        app: webcolor1
    spec:
      containers:
      - name: webcolor
        image: fabricioveronez/web-page:green
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webcolor1
spec:
  selector:
    app: webcolor1
  ports:
  - port: 80  
    targetPort: 80

